spring:
  cloud:
    gateway:
      routes:

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast # 路由给renren-fast，lb代表负载均衡
          predicates:  # 什么情况下路由给它
            - Path=/api/** # 默认前端项目都带上api前缀，
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: nginx_route
          uri: lb://mall-product
          predicates:
            - Host=mall.com,item.mall.com

        - id: search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: mall_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com

        - id: mall_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com
